### ISSUE TITLE
Psr4Resolver issue on Windows

### ISSUE THREAD

**Issue by underdpt** [lorisleiva/lody#1]
Hello,

I'm trying to automatically register commands on laravel-actions, but found that this isn't working on windows.

I've tracked it down to `vendor\lorisleiva\lody\src\Psr4Resolver.php`, on method `findPrefixes` you have:

```php
public function findPrefixes(string $filename): array
{
    $directory = $this->getPsr4Dictionary();
    $fragments = array_reverse(explode(DIRECTORY_SEPARATOR, $filename));
    $accumulator = $filename;

    foreach ($fragments as $fragment) {
        $accumulator = Str::beforeLast($accumulator, DIRECTORY_SEPARATOR.$fragment);

        if ($classPrefix = ($directory[$accumulator] ?? false)) {
            return [realpath($accumulator).DIRECTORY_SEPARATOR, $classPrefix];
        }
    }

    return ['', ''];
}
```

I see two issues related with windows paths:

First, `getPsr4Dictionary` method returns an array of paths, but on windows they have a mixed directory separators:

```
array:201 [
  "D:\desarrollos\enertrade.es\api.enertrade.es\vendor/voku/portable-ascii/src/voku" => "voku\"
  "D:\desarrollos\enertrade.es\api.enertrade.es\vendor/phpdocumentor/reflection-common/src" => "phpDocumentor\Reflection\"
  "D:\desarrollos\enertrade.es\api.enertrade.es\vendor/phpdocumentor/reflection-docblock/src" => "phpDocumentor\Reflection\"
  "D:\desarrollos\enertrade.es\api.enertrade.es\vendor/phpdocumentor/type-resolver/src" => "phpDocumentor\Reflection\"
  "D:\desarrollos\enertrade.es\api.enertrade.es\vendor/hisorange/browser-detect/src" => "hisorange\BrowserDetect\"
  "D:\desarrollos\enertrade.es\api.enertrade.es\vendor/maennchen/zipstream-php/src" => "ZipStream\"
...
]
```

Then `$fragments` on linux is an array:

```
array:9 [
  0 => "ActualizaConfiguracionesCamposPortugal.php"
  1 => "Configuradores"
  2 => "Actions"
  3 => "app"
  4 => "intranet"
  5 => "enertrade"
  6 => "vagrant"
  7 => "home"
  8 => ""
]
```

But on windows you have the drive letter
```
array:8 [
  0 => "ActualizaConfiguracionesCamposPortugal.php"
  1 => "Configuradores"
  2 => "Actions"
  3 => "app"
  4 => "api.enertrade.es"
  5 => "enertrade.es"
  6 => "desarrollos"
  7 => "D:"
]
```

As you prepend `DIRECTORY_SEPARATOR` to each fragment, to search for `$classPrefix` and they're mixed, but also there's no leading `DIRECTORY_SEPARATOR` on windows but a drive letter, it fails to find the any `$classPrefix`.

I'm sorry I'm not sure I understand how the whole thing works and how you would like this to be solved, I cannot send a PR for this.

**Comment by lorisleiva** [comment]
Hey 👋 sorry for the late reply, I finally had the time to check this out and I've created a PR that should add support for Windows paths. I've added `windows-latest` to the GitHub actions operating systems as well so we know if something breaks in the future.

I'll now work on adding support for Laravel 9 and then I'll tag a new release. 🙂

**Comment by underdpt** [comment]
Thank you!

**Comment by lorisleiva** [comment]
@underdpt No worries. It's been tagged as `v0.3.0`. 🚀🙂
