### ISSUE TITLE
Empty class array return 

### ISSUE THREAD

**Issue by inkomomutane** [lorisleiva/lody#7]
Hi @lorisleiva  
Has a way to get class names of files without transforming directly to classnames?
Example:
```path
Company\sales\src\Events\SendOrderEvent.php
```
to 
```php 
Company\Sales\Events\SendOrderEvent
```
My module composer.json
```json 
 "Company\\Sales\\": "src/",

**Comment by lorisleiva** [comment]
Hi there, sorry I don't understand the question.

**Comment by inkomomutane** [comment]
> Hi there, sorry I don't understand the question.

Oh my English is bad. 

I want to know, if has a way to get the a class namespace of ``SendOrderEvent.php`` 
```php 
Company\Sales\Events\SendOrderEvent
```
that the folder structure is this: 
``` 
Company/
   └── sales/
          └── src/
                 └── Events/
                           └── SendOrderEvent.php
 ```
 And not 
 
 ``` 
Company/
   └── Sales/
         └── Events/
                 └── SendOrderEvent.php
 ```

**Comment by lorisleiva** [comment]
By default, classname resolution uses the `autoload` property of your `composer.json` to figure out how to construct your classes. 

So in your case, you'd need something like:

```json
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Company\\Sales\\": "Company/Sales/src/"
        }
    },
```

[You can read more about it here](https://github.com/lorisleiva/lody?tab=readme-ov-file#resolving-classnames).
